version: "3.8"

services:
  app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT
    volumes:
      - ./index.js:/app/index.js
      - ./src:/app/src
      - ./openapi.yml:/app/openapi.yml
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  pgdata:
