version: "3.8"

services:
  app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT
    volumes:
      - ./index.js:/app/index.js
      - ./src:/app/src

